name: deepseek
description: >
  A DeepSeek client for dart and flutter. Seamless integration of AI models for text generation and chat.

version: 1.2.1
repository: https://github.com/tempo-riz/deepseek-dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  will_it_run: ^1.0.4
  dotenv: ^4.2.0
